/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 10.11.14-MariaDB-0+deb12u2-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `payments` (
	`id` int (10),
	`payments_id` int (10),
	`contracts_id` int (10),
	`period_year` smallint (5),
	`period_month` tinyint (3),
	`amount` Decimal (14),
	`payment_date` date ,
	`note` text ,
	`payment_batch_id` varchar (108),
	`payment_method` char (21),
	`bank_accounts_id` int (10),
	`payment_type` char (42),
	`valid_from` datetime ,
	`valid_to` datetime ,
	`valid_user_from` int (10),
	`valid_user_to` int (10)
); 
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('243','243','30','2020','9','1100.00','2020-10-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('244','244','30','2020','10','1100.00','2020-11-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('245','245','30','2020','11','1100.00','2020-12-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('246','246','30','2020','12','1100.00','2021-01-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('247','247','30','2021','1','1100.00','2021-01-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('248','248','30','2021','2','1100.00','2021-02-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('249','249','30','2021','3','1100.00','2021-03-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('250','250','30','2021','4','1100.00','2021-04-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('251','251','30','2021','5','1100.00','2021-05-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('252','252','30','2021','6','1100.00','2021-06-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('253','253','30','2021','7','1100.00','2021-07-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('254','254','30','2021','8','1100.00','2021-08-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('255','255','30','2021','9','1100.00','2021-09-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('256','256','30','2021','10','1100.00','2021-10-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('257','257','30','2021','11','1300.00','2021-11-24','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('258','258','30','2021','12','1300.00','2021-12-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('259','259','30','2022','1','1300.00','2022-01-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('260','260','30','2022','2','1300.00','2022-02-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('261','261','30','2022','3','1300.00','2022-03-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('262','262','30','2022','4','1300.00','2022-04-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('263','263','30','2022','5','1300.00','2022-05-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('264','264','30','2022','6','1300.00','2022-06-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('265','265','30','2022','7','1300.00','2022-07-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('266','266','30','2022','8','1300.00','2022-08-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('267','267','30','2022','9','1600.00','2022-09-09','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('268','268','30','2022','10','1600.00','2022-10-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('269','269','30','2022','11','1600.00','2022-11-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('270','270','30','2022','12','1600.00','2022-12-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('271','271','30','2023','1','1600.00','2023-01-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('272','272','30','2023','2','1600.00','2023-02-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('273','273','30','2023','3','1600.00','2023-03-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('274','274','30','2023','4','1600.00','2023-04-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('275','275','30','2023','5','1600.00','2023-05-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('276','276','30','2023','6','1600.00','2023-06-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('277','277','30','2023','7','1600.00','2023-07-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('278','278','30','2023','8','1600.00','2023-08-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('279','279','30','2023','9','1600.00','2023-09-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('280','280','30','2023','10','1600.00','2023-10-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('281','281','30','2023','11','1600.00','2023-11-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('282','282','30','2023','12','1600.00','2023-12-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('283','283','30','2024','1','1600.00','2024-01-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('284','284','30','2024','2','1600.00','2024-02-10','Tereza Malinčíková – nájem garáž',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
insert into `payments` (`id`, `payments_id`, `contracts_id`, `period_year`, `period_month`, `amount`, `payment_date`, `note`, `payment_batch_id`, `payment_method`, `bank_accounts_id`, `payment_type`, `valid_from`, `valid_to`, `valid_user_from`, `valid_user_to`) values('285','285','30','2024','3','800.00','2024-03-09','Tereza Malinčíková – nájem garáž (polovina, konec 13.3.2024)',NULL,'account','1','rent','2026-02-04 13:46:08',NULL,NULL,NULL);
